### ISSUE TITLE
yarn install fails at space-js@0.0.1 prebuild script

### ISSUE THREAD

**Issue by nandit123** [FleekHQ/space-sdk#1]
After cloning the repo, when i run `yarn install`, i am getting the following error output - 
```
Invalid switch - "".
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! space-js@0.0.1 prebuild: `del dist/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the space-js@0.0.1 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
```

**Comment by jsonsivar** [comment]
Hi @nandit123 , which branch did you try? I just tried it and it worked for me.  I noticed `Invalid switch - "".` at the top of the logs, is there a chance there is some typo there?

**Comment by nandit123** [comment]
works after replacing **prebuild** scrpit '`del dist/`' in package.json file with '`del dist`' on windows
